puts "🌱 Seeding spices..."

# Seed your database here

Movie.create(title: "Tropic Thunder", thumbnail_url: "https://upload.wikimedia.org/wikipedia/en/d/d6/Tropic_thunder_ver3.jpg", director: "Ben Stiller", description: "Through a series of freak occurrences, a group of actors shooting a big-budget war movie are forced to become the soldiers they are portraying.", budget: 92.0, box_office_return: 195.7)
Movie.create(title: "Tenet", thumbnail_url: "https://upload.wikimedia.org/wikipedia/en/1/14/Tenet_movie_poster.jpg", director: "Christopher Nolan", description: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.", budget: 205.0, box_office_return: 365.3)
Movie.create(title: "The Dark Knight", thumbnail_url: "https://en.wikipedia.org/wiki/File:The_Dark_Knight_(2008_film).jpg", director: "Christopher Nolan", description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", budget: 185.0, box_office_return: 1000.0)
Movie.create(title: "True Grit", thumbnail_url: "https://upload.wikimedia.org/wikipedia/en/c/ce/True_Grit_Poster.jpg", director: "Joel and Ethan Coen", description: "A stubborn teenager enlists the help of a tough U.S. Marshal to track down her father's murderer.", budget: 38.0, box_office_return: 252.3)
Movie.create(title: "No Country for Old Men", thumbnail_url: "https://upload.wikimedia.org/wikipedia/en/8/8b/No_Country_for_Old_Men_poster.jpg", director: "Joel and Ethan Coen", description: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.", budget: 25.0, box_office_return: 171.6)
Movie.create(title: "The Prestige", thumbnail_url: "https://upload.wikimedia.org/wikipedia/en/d/d2/Prestige_poster.jpg", director: "Christopher Nolan", description: "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.", budget: 40.0, box_office_return: 109.7)
Movie.create(title: "3:10 to Yuma", thumbnail_url: "https://upload.wikimedia.org/wikipedia/en/2/27/310_to_Yuma_%282007_film%29.jpg", director: "James Mangold", description: "A small-time rancher agrees to hold a captured outlaw who's awaiting a train to go to court in Yuma. A battle of wills ensues as the outlaw tries to psych out the rancher.", budget: 55.0, box_office_return: 71.2)
Movie.create(title: "Water World", thumbnail_url: "https://upload.wikimedia.org/wikipedia/en/5/5f/Waterworld.jpg", director: "Kevin Reynolds", description: "In a future where the polar ice-caps have melted and Earth is almost entirely submerged, a mutated mariner fights starvation and outlaw smokers and reluctantly helps a woman and a young girl try to find dry land.", budget: 175.0, box_office_return: 264.2)
Movie.create(title: "Zoolander", thumbnail_url: "https://upload.wikimedia.org/wikipedia/en/7/7c/Movie_poster_zoolander.jpg", director: "Ben Stiller", description: "Derek and Hansel are lured into modelling again, in Rome, where they find themselves the target of a sinister conspiracy.", budget: 28.0, box_office_return: 60.8)
Movie.create(title: "Talladega Nights: The Ballad of Ricky Bobby", thumbnail_url: "https://upload.wikimedia.org/wikipedia/en/e/e7/Talladega_nights.jpg", director: "Adam McKay", description: "Number one NASCAR driver Ricky Bobby stays atop the heap thanks to a pact with his best friend and teammate, Cal Naughton, Jr. But when a French Formula One driver, makes his way up the ladder, Ricky Bobby's talent and devotion are put to the test.", budget: 72.5, box_office_return: 163.4)


puts "✅ Done seeding!"
